export interface Feature {
  id: string;
  title: string;
  description: string;
  icon: string;
  category: "mobile" | "desktop" | "both";
  platform: "mobile" | "desktop" | "both";
}

export const featuresDe: Feature[] = [
  {
    id: "probenerfassung",
    title: "Probenerfassung",
    description: "Materialproben mit automatischer ID, Tiefe, Schicht, Schadstoffklassifizierung und Koordinaten direkt auf dem Grundriss verorten.",
    icon: "🔬",
    category: "both",
    platform: "both",
  },
  {
    id: "sondierungserfassung",
    title: "Sondierungserfassung",
    description: "Bohrpunkte und Kernbohrungen mit Tiefenprofil, Schichtbeschreibung und Koordinaten erfassen. Normkonform nach VDI 6202.",
    icon: "⛏️",
    category: "both",
    platform: "both",
  },
  {
    id: "raumerfassung",
    title: "Raumerfassung",
    description: "Räume mit Maßen, Materialien, Zustandsbeschreibung und Schadstoffbelastung strukturiert aufnehmen — direkt verknüpft mit dem Grundriss.",
    icon: "🏠",
    category: "both",
    platform: "both",
  },
  {
    id: "mengenermittlung",
    title: "Mengenermittlung",
    description: "Automatische Berechnung von Flächen, Volumen und Mengen aus den Raumdaten. Exportierbar als Excel oder PDF für Ausschreibungen.",
    icon: "📐",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "planerstellung",
    title: "Planerstellung",
    description: "Eigene Grundrisse als Planvorlage hochladen, Proben- und Raummarker setzen und fertige Pläne mit Legende exportieren.",
    icon: "🗺️",
    category: "both",
    platform: "both",
  },
  {
    id: "fotodokumentation",
    title: "Fotodokumentation",
    description: "Fotos direkt mit Probe, Raum oder Sondierung verknüpfen. Automatischer Zeitstempel und GPS-Tag. Kein manuelles Zuordnen mehr.",
    icon: "📷",
    category: "mobile",
    platform: "mobile",
  },
  {
    id: "projektmanagement",
    title: "Projektmanagement",
    description: "Mehrere Projekte parallel verwalten, Bauvorhaben anlegen, Status tracken und das Team koordinieren — auf Desktop und Tablet.",
    icon: "📁",
    category: "both",
    platform: "both",
  },
  {
    id: "probenmanagement",
    title: "Probenmanagement",
    description: "Vollständige Übersicht aller Proben mit Labor-ID, Einreichungsstatus, Analyseergebnissen und Grenzwertüberschreitungen.",
    icon: "🗂️",
    category: "both",
    platform: "both",
  },
  {
    id: "labor-workflow",
    title: "Labor-Workflow",
    description: "Proben ans Labor übergeben, Laborergebnisse einpflegen, Grenzwerte prüfen und Auswertung direkt in den Bericht übernehmen.",
    icon: "🧪",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "entsorgung",
    title: "Entsorgung & Nachweise",
    description: "Wiegescheine, Übernahme-, Begleit-, Liefer- und Annahmescheine erfassen. Der Abfallschlüssel (AVV) wird klassifiziert und ab 2 t bzw. 20 t automatisch als nachweispflichtig erkannt.",
    icon: "♻️",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "abrechnungspruefung",
    title: "Abrechnungsprüfung",
    description: "Eingehende Rechnungen automatisch gegen die eigene Soll-Ermittlung prüfen — Abweichungen fallen auf, bevor sie bezahlt werden.",
    icon: "🧾",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "portfolio",
    title: "Portfolio-Übersicht",
    description: "Alle Projekte und die Auslastung des Teams auf einen Blick — als Board über die gesamte Auftragslage statt Projekt für Projekt.",
    icon: "📊",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "gutachten-scan",
    title: "Gutachten-Scan",
    description: "Bestehende Gutachten einscannen und importieren, statt Altdaten von Hand zu übertragen — Text wird automatisch erkannt und zugeordnet.",
    icon: "📄",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "termine",
    title: "Termine & Kalender",
    description: "Ortstermine und Fristen direkt im Projekt planen, mit iCal-Export für den eigenen Kalender.",
    icon: "📅",
    category: "both",
    platform: "both",
  },
];

export const featuresEn: Feature[] = [
  {
    id: "probenerfassung",
    title: "Sample Collection",
    description: "Capture material samples with automatic ID, depth, layer, pollutant classification and coordinates — placed directly on the floor plan.",
    icon: "🔬",
    category: "both",
    platform: "both",
  },
  {
    id: "sondierungserfassung",
    title: "Survey / Drilling Capture",
    description: "Record boreholes and core drillings with depth profiles, layer descriptions and coordinates. Compliant with VDI 6202.",
    icon: "⛏️",
    category: "both",
    platform: "both",
  },
  {
    id: "raumerfassung",
    title: "Room Capture",
    description: "Structured room surveys covering dimensions, materials, condition and pollutant load — directly linked to the floor plan.",
    icon: "🏠",
    category: "both",
    platform: "both",
  },
  {
    id: "mengenermittlung",
    title: "Quantity Estimation",
    description: "Automatic calculation of areas, volumes and quantities from room data. Exportable as Excel or PDF for tendering.",
    icon: "📐",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "planerstellung",
    title: "Plan Creation",
    description: "Upload floor plans as templates, place sample and room markers, and export finished plans with legends.",
    icon: "🗺️",
    category: "both",
    platform: "both",
  },
  {
    id: "fotodokumentation",
    title: "Photo Documentation",
    description: "Link photos directly to samples, rooms or drillings. Automatic timestamp and GPS tag — no manual assignment needed.",
    icon: "📷",
    category: "mobile",
    platform: "mobile",
  },
  {
    id: "projektmanagement",
    title: "Project Management",
    description: "Manage multiple projects in parallel, create construction sites, track status and coordinate the team — on desktop and tablet.",
    icon: "📁",
    category: "both",
    platform: "both",
  },
  {
    id: "probenmanagement",
    title: "Sample Management",
    description: "Full overview of all samples with lab ID, submission status, analysis results and limit exceedances.",
    icon: "🗂️",
    category: "both",
    platform: "both",
  },
  {
    id: "labor-workflow",
    title: "Lab Workflow",
    description: "Submit samples to the lab, enter results, check against limits and pull the evaluation directly into your report.",
    icon: "🧪",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "entsorgung",
    title: "Disposal & Manifests",
    description: "Capture weighbridge slips, transfer, accompanying, delivery and acceptance notes. The waste code (AVV) gets classified, and shipments above 2t/20t are automatically flagged as manifest-required.",
    icon: "♻️",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "abrechnungspruefung",
    title: "Invoice Audit",
    description: "Incoming invoices are checked automatically against your own quantity estimate — discrepancies surface before you pay.",
    icon: "🧾",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "portfolio",
    title: "Portfolio Overview",
    description: "Every project and your team's workload at a glance — a board across the whole pipeline, not project by project.",
    icon: "📊",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "gutachten-scan",
    title: "Report Scan Import",
    description: "Scan and import existing expert reports instead of retyping legacy data — text is recognised and matched automatically.",
    icon: "📄",
    category: "desktop",
    platform: "desktop",
  },
  {
    id: "termine",
    title: "Appointments & Calendar",
    description: "Plan site visits and deadlines directly in the project, with iCal export to your own calendar.",
    icon: "📅",
    category: "both",
    platform: "both",
  },
];

export const features: Feature[] = featuresDe;

export const getFeaturesForLang = (lang: "de" | "en"): Feature[] =>
  lang === "en" ? featuresEn : featuresDe;
